// Code generated by goctl. DO NOT EDIT.
package types

type AuthReq struct {
	AuthCode string `json:"authcode"`
	Passwd   string `json:"passwd"`
}

type AuthResp struct {
	Status string `json:"status"`
	Cookie string `json:"cookie"`
}

type GetSubjectReq struct {
	Cookie string `json:"cookie"`
}

type GetSubjectResp struct {
	Weekly    string `json:"weekly"`
	Lession1  string `json:"lession1"`
	Src1      bool   `json:"src1"`
	Teacher1  string `json:"teacher1"`
	Lession2  string `json:"lession2"`
	Src2      bool   `json:"src2"`
	Teacher2  string `json:"teacher2"`
	Lession3  string `json:"lession3"`
	Src3      bool   `json:"src3"`
	Teacher3  string `json:"teacher3"`
	Lession4  string `json:"lession4"`
	Src4      bool   `json:"src4"`
	Teacher4  string `json:"teacher4"`
	Lession5  string `json:"lession5"`
	Src5      bool   `json:"src5"`
	Teacher5  string `json:"teacher5"`
	Lession6  string `json:"lession6"`
	Src6      bool   `json:"src6"`
	Teacher6  string `json:"teacher6"`
	Lession7  string `json:"lession7"`
	Src7      bool   `json:"src7"`
	Teacher7  string `json:"teacher7"`
	Lession8  string `json:"lession8"`
	Src8      bool   `json:"src8"`
	Teacher8  string `json:"teacher8"`
	Lession9  string `json:"lession9"`
	Src9      bool   `json:"src9"`
	Teacher9  string `json:"teacher9"`
	Lession10 string `json:"lession10"`
	Src10     bool   `json:"src10"`
	Teacher10 string `json:"teacher10"`
	Lession11 string `json:"lession11"`
	Src11     bool   `json:"src11"`
	Teacher11 string `json:"teacher11"`
	Lession12 string `json:"lession12"`
	Src12     bool   `json:"src12"`
	Teacher12 string `json:"teacher12"`
	Lession13 string `json:"lession13"`
	Src13     bool   `json:"src13"`
	Teacher13 string `json:"teacher13"`
	Lession14 string `json:"lession14"`
	Src14     bool   `json:"src14"`
	Teacher14 string `json:"teacher14"`
}

type GetTomrowSubjReq struct {
	Cookie string `json:"cookie"`
}

type GetTomrowSubjResp struct {
	Weekly    string `json:"weekly"`
	Lession1  string `json:"lession1"`
	Src1      bool   `json:"src1"`
	Teacher1  string `json:"teacher1"`
	Lession2  string `json:"lession2"`
	Src2      bool   `json:"src2"`
	Teacher2  string `json:"teacher2"`
	Lession3  string `json:"lession3"`
	Src3      bool   `json:"src3"`
	Teacher3  string `json:"teacher3"`
	Lession4  string `json:"lession4"`
	Src4      bool   `json:"src4"`
	Teacher4  string `json:"teacher4"`
	Lession5  string `json:"lession5"`
	Src5      bool   `json:"src5"`
	Teacher5  string `json:"teacher5"`
	Lession6  string `json:"lession6"`
	Src6      bool   `json:"src6"`
	Teacher6  string `json:"teacher6"`
	Lession7  string `json:"lession7"`
	Src7      bool   `json:"src7"`
	Teacher7  string `json:"teacher7"`
	Lession8  string `json:"lession8"`
	Src8      bool   `json:"src8"`
	Teacher8  string `json:"teacher8"`
	Lession9  string `json:"lession9"`
	Src9      bool   `json:"src9"`
	Teacher9  string `json:"teacher9"`
	Lession10 string `json:"lession10"`
	Src10     bool   `json:"src10"`
	Teacher10 string `json:"teacher10"`
	Lession11 string `json:"lession11"`
	Src11     bool   `json:"src11"`
	Teacher11 string `json:"teacher11"`
	Lession12 string `json:"lession12"`
	Src12     bool   `json:"src12"`
	Teacher12 string `json:"teacher12"`
	Lession13 string `json:"lession13"`
	Src13     bool   `json:"src13"`
	Teacher13 string `json:"teacher13"`
	Lession14 string `json:"lession14"`
	Src14     bool   `json:"src14"`
	Teacher14 string `json:"teacher14"`
}

type ChangeSubjReq struct {
	ClassCode string `json:"classcode"`
	Weekly    string `json:"weekly1"`
	Lession1  string `json:"lession1"`
	Src1      bool   `json:"src1"`
	Teacher1  string `json:"teacher1"`
	Lession2  string `json:"lession2"`
	Src2      bool   `json:"src2"`
	Teacher2  string `json:"teacher2"`
	Lession3  string `json:"lession3"`
	Src3      bool   `json:"src3"`
	Teacher3  string `json:"teacher3"`
	Lession4  string `json:"lession4"`
	Src4      bool   `json:"src4"`
	Teacher4  string `json:"teacher4"`
	Lession5  string `json:"lession5"`
	Src5      bool   `json:"src5"`
	Teacher5  string `json:"teacher5"`
	Lession6  string `json:"lession6"`
	Src6      bool   `json:"src6"`
	Teacher6  string `json:"teacher6"`
	Lession7  string `json:"lession7"`
	Src7      bool   `json:"src7"`
	Teacher7  string `json:"teacher7"`
	Lession8  string `json:"lession8"`
	Src8      bool   `json:"src8"`
	Teacher8  string `json:"teacher8"`
	Lession9  string `json:"lession9"`
	Src9      bool   `json:"src9"`
	Teacher9  string `json:"teacher9"`
	Lession10 string `json:"lession10"`
	Src10     bool   `json:"src10"`
	Teacher10 string `json:"teacher10"`
	Lession11 string `json:"lession11"`
	Src11     bool   `json:"src11"`
	Teacher11 string `json:"teacher11"`
	Lession12 string `json:"lession12"`
	Src12     bool   `json:"src12"`
	Teacher12 string `json:"teacher12"`
	Lession13 string `json:"lession13"`
	Src13     bool   `json:"src13"`
	Teacher13 string `json:"teacher13"`
	Lession14 string `json:"lession14"`
	Src14     bool   `json:"src14"`
	Teacher14 string `json:"teacher14"`
}

type ChangeSubjResp struct {
	Status string `json:"status"`
}

type ClassMsgReq struct {
	Cookie string `json:"cookie"`
}

type ClassMsgResp struct {
	Msgid     int64  `json:"msgid"`
	Msg       string `json:"msg"`
	MsgTitle  string `json:"msgtitle"`
	ClassCode string `json:"classcode"`
	Time      string `json:"time"`
	Sender    string `json:"sender"`
}

type AdminMsgReq struct {
	Msg       string `json:"msg"`
	MsgTitle  string `json:"msgtitle"`
	ClassCode string `json:"classcode"`
	Sender    string `json:"sender"`
}

type AdminMsgResp struct {
	Status string `json:"status"`
}

type AdminGetSubjReq struct {
	ClassCode string `json:"classcode"`
	Weekly    string `json:"weekly"`
}

type AdminGetSubjResp struct {
	Lession1  string `json:"lession1"`
	Src1      bool   `json:"src1"`
	Teacher1  string `json:"teacher1"`
	Lession2  string `json:"lession2"`
	Src2      bool   `json:"src2"`
	Teacher2  string `json:"teacher2"`
	Lession3  string `json:"lession3"`
	Src3      bool   `json:"src3"`
	Teacher3  string `json:"teacher3"`
	Lession4  string `json:"lession4"`
	Src4      bool   `json:"src4"`
	Teacher4  string `json:"teacher4"`
	Lession5  string `json:"lession5"`
	Src5      bool   `json:"src5"`
	Teacher5  string `json:"teacher5"`
	Lession6  string `json:"lession6"`
	Src6      bool   `json:"src6"`
	Teacher6  string `json:"teacher6"`
	Lession7  string `json:"lession7"`
	Src7      bool   `json:"src7"`
	Teacher7  string `json:"teacher7"`
	Lession8  string `json:"lession8"`
	Src8      bool   `json:"src8"`
	Teacher8  string `json:"teacher8"`
	Lession9  string `json:"lession9"`
	Src9      bool   `json:"src9"`
	Teacher9  string `json:"teacher9"`
	Lession10 string `json:"lession10"`
	Src10     bool   `json:"src10"`
	Teacher10 string `json:"teacher10"`
	Lession11 string `json:"lession11"`
	Src11     bool   `json:"src11"`
	Teacher11 string `json:"teacher11"`
	Lession12 string `json:"lession12"`
	Src12     bool   `json:"src12"`
	Teacher12 string `json:"teacher12"`
	Lession13 string `json:"lession13"`
	Src13     bool   `json:"src13"`
	Teacher13 string `json:"teacher13"`
	Lession14 string `json:"lession14"`
	Src14     bool   `json:"src14"`
	Teacher14 string `json:"teacher14"`
}
