const rejson = {
	durl: "https://class.dabaostudio.xyz",
	classcode: "null",
	publicpwd: "xjcwxgk-db2333",
	zhiri: "",
	lastmsgtime: "",
	tomorrow: 0,
	weekly: "",
	lession1: "",
	src1: "",
	teacher1: "",
	lession2: "",
	src2: "",
	teacher2: "",
	lession3: "",
	src3: "",
	teacher3: "",
	lession4: "",
	src4: "",
	teacher4: "",
	lession5: "",
	src5: "",
	teacher5: "",
	lession6: "",
	src6: "",
	teacher6: "",
	lession7: "",
	src7: "",
	teacher7: "",
	lession8: "",
	src8: "",
	teacher8: "",
	lession9: "",
	src9: "",
	teacher9: "",
	lession10: "",
	src10: "",
	teacher10: "",
	lession11: "",
	src11: "",
	teacher11: "",
	lession12: "",
	src12: "",
	teacher12: "",
	lession13: "",
	src13: "",
	teacher13: "",
	msgid: 0,
	msg:"",
	msgtitle:"",
};
export default rejson;
