// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"backend/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/auth",
				Handler: AuthHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/class/getsubject",
				Handler: GetSubjectHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/class/gettomrowsubj",
				Handler: GetTomrowSubjHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/admin/changesubj",
				Handler: ChangeSubjHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/class/getmsg",
				Handler: ClassMsgHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/admin/setmsg",
				Handler: AdminMsgHandler(serverCtx),
			},
		},
	)
}
